version: '3.1'

services:
  dialog:
    build: ./web_api
    working_dir: /dialog_api
    tty: true
    ports: 
      - "8000:8000"
    volumes:
      - ./web_api:/dialog_api
    command: sh -c "cd /dialog_api && uvicorn main:app --reload --host 0.0.0.0 --port 8000"

  web_client:
    build: ./web_client
    working_dir: /web_client
    tty: true
    ports: 
      - "3000:3000"
    volumes:
      - ./web_client/app:/web_client
    command: sh -c "npm install && npm start"
  
  voicevox_engine:
    # CPUの場合は voicevox/voicevox_engine:cpu-ubuntu20.04-latest を使用
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
    ports:
      - "50021:50021"
    tty: true
    volumes:
      - ./voicevox_engine:/app/voicevox_engine
    #
    # 以下の項目はCPUの場合はなくても大丈夫
    #
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]